<a href="https://colab.research.google.com/github/G-eethu/Geethu-learn.py/blob/main/TASK_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [2]:
#please type your answer below this line.
import numpy as np 
mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)
print("Trace of the Array is: \n",mat.trace())

Array
 [[ 9  6  1  5]
 [13 11 10  5]
 [13  9  4  3]
 [ 2  2 11  0]]
Trace of the Array is: 
 24


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [3]:
#please type your answer below this line.
import numpy as np
mat = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("Matix\n",mat)
print("\nThe Inverse of Matrix is :\n",np.linalg.inv(mat))

Matix
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

The Inverse of Matrix is :
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [4]:
#please type your answer below this line.
import numpy as np 
mat = np.random.randint(0,8,(3,3))
print("Array\n",mat)
print("\nThe Norm of the Matrix is\n",np.linalg.norm(mat))

Array
 [[7 1 3]
 [5 2 6]
 [3 2 7]]

The Norm of the Matrix is
 13.638181696985855


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [5]:
#please type your answer below this line.
import numpy as np
mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)
print("\nThe EigenValue and EigenVectors of the Matrix is\n",np.linalg.eig(mat))

Array
 [[14  2  3  9]
 [13 12 13 14]
 [ 0 12  6  5]
 [11 12  0  7]]

The EigenValue and EigenVectors of the Matrix is
 (array([33.99974235, 11.57620409, -0.90181702, -5.67412943]), array([[ 0.33743795,  0.52820578,  0.41847963, -0.32996141],
       [ 0.72273225, -0.41223718,  0.16632067, -0.51049447],
       [ 0.39165554, -0.71795594,  0.31583745,  0.19507597],
       [ 0.45869343,  0.18867546, -0.83514007,  0.76971828]]))
