<a href="https://colab.research.google.com/github/G-eethu/Geethu-learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [1]:
#please enter your code below this line.
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)
sum = np.sum(mat)
print("\n Sum is :\n",sum)


 The Matrix is:
 [[3 7 5]
 [0 5 2]
 [0 0 0]]

 Sum is :
 22


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [2]:
#please enter your code below this line.
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)
col = np.sum(mat,axis =0)
print("\n Sum of Columns:\n",col)
row = np.sum(mat,axis =1)
print("\n Sum of Columns:\n",row)


 The Matrix is:
 [[7 2 2]
 [5 2 1]
 [0 4 6]]

 Sum of Columns:
 [12  8  9]

 Sum of Columns:
 [11  8 10]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [3]:
#please enter your code belowthis line.
import numpy as np
mat = np.random.randint(0,15,(4,4))
print("\n The Matrix is:\n",mat) 
min = np.min(mat)
print("\n Minimum Value is\n",min) 
max = np.max(mat)
print("\n Maximum Value is\n",max) 
mean = np.mean(mat)
print("\n Minimum Value is\n",mean)


 The Matrix is:
 [[12 12 12  0]
 [ 3  4  9 10]
 [ 2  6 10 12]
 [ 8 13 12  1]]

 Minimum Value is
 0

 Maximum Value is
 13

 Minimum Value is
 7.875


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [4]:
#please enter your code below this line.
import numpy as np
mat = np.random.randint(0,99,(10,10))
print("\n The Matrix is:\n",mat)
print("\nThe 7th row is :\n",mat[7,:]) 
print("\nThe 4-8th row is :\n",mat[4:8,:])
print("\nThe value at (5,5) is :\n",mat[5,5]) 
print("\nThe 5th column) is :\n",mat[:,5])
print("\nThe 2-5th column) is :\n",mat[:,2:5])


 The Matrix is:
 [[87 70 55 84 12  1 13  6 73 88]
 [95 98  7 53  1 82 73  2 53 82]
 [44 26 89 28 21 84 20 95 77 67]
 [95 95  6 37  5 28 72 33 16 59]
 [98 49 96 75 49 34 80 49 15 97]
 [26 46 11  9 33 45 85 16  3 25]
 [17  4 89 16 31 55 64 10 50  4]
 [ 2 43 12 23 22 80 48 25 27 60]
 [85  0 78  7 60 72  2 55 63 80]
 [84 96 83 15 77 76 51 21  8 70]]

The 7th row is :
 [ 2 43 12 23 22 80 48 25 27 60]

The 4-8th row is :
 [[98 49 96 75 49 34 80 49 15 97]
 [26 46 11  9 33 45 85 16  3 25]
 [17  4 89 16 31 55 64 10 50  4]
 [ 2 43 12 23 22 80 48 25 27 60]]

The value at (5,5) is :
 45

The 5th column) is :
 [ 1 82 84 28 34 45 55 80 72 76]

The 2-5th column) is :
 [[55 84 12]
 [ 7 53  1]
 [89 28 21]
 [ 6 37  5]
 [96 75 49]
 [11  9 33]
 [89 16 31]
 [12 23 22]
 [78  7 60]
 [83 15 77]]
