<a href="https://colab.research.google.com/github/G-eethu/Geethu-learn.py/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [2]:
#please type your answer below this line.
import numpy as np 
 
mat1 = np.random.randint(0,8,(3,3))
mat2 = np.random.randint(10,19,(3,3))   
print("Matrix A\n" ,mat1)  
print("\nMatrix B\n" ,mat2) 
out = np.multiply.outer(mat1,mat2)
print("Outer Products\n",out) 
dot = np.dot(mat1,mat2)
print("Dot Products\n",dot) 
Ele = np.multiply(mat1,mat2)
print("Element Wise\n",Ele)

Matrix A
 [[3 7 3]
 [6 3 2]
 [7 2 3]]

Matrix B
 [[10 14 18]
 [10 10 18]
 [11 11 15]]
Outer Products
 [[[[ 30  42  54]
   [ 30  30  54]
   [ 33  33  45]]

  [[ 70  98 126]
   [ 70  70 126]
   [ 77  77 105]]

  [[ 30  42  54]
   [ 30  30  54]
   [ 33  33  45]]]


 [[[ 60  84 108]
   [ 60  60 108]
   [ 66  66  90]]

  [[ 30  42  54]
   [ 30  30  54]
   [ 33  33  45]]

  [[ 20  28  36]
   [ 20  20  36]
   [ 22  22  30]]]


 [[[ 70  98 126]
   [ 70  70 126]
   [ 77  77 105]]

  [[ 20  28  36]
   [ 20  20  36]
   [ 22  22  30]]

  [[ 30  42  54]
   [ 30  30  54]
   [ 33  33  45]]]]
Dot Products
 [[133 145 225]
 [112 136 192]
 [123 151 207]]
Element Wise
 [[30 98 54]
 [60 30 36]
 [77 22 45]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [3]:
#please type your answer below this line.
import numpy as np 
mat = np.random.randint(0,16,(4,4))
print("Matrix is \n", mat) 
#adding 4(scalar)to the matrix
scal = 2
addScal = mat + scal
print("\n Scalar Matrix\n",addScal) 
#matrix broadcasting
nums = np.array([1,2,3,4])
mult = mat * nums
print("\nThe Multiplication by broadcasting\n",mult)

Matrix is 
 [[ 3  2  6 11]
 [ 3 15  2  1]
 [13  7  9  1]
 [ 7 12 14  8]]

 Scalar Matrix
 [[ 5  4  8 13]
 [ 5 17  4  3]
 [15  9 11  3]
 [ 9 14 16 10]]

The Multiplication by broadcasting
 [[ 3  4 18 44]
 [ 3 30  6  4]
 [13 14 27  4]
 [ 7 24 42 32]]
